/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Diamonds__factory } from './Diamonds__factory.js';
export { Migrations__factory } from './Migrations__factory.js';