// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface console$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "console";
  readonly sourceName: "contracts/util/console.sol";
  readonly abi: [];
  readonly bytecode: "0x60556032600b8282823980515f1a607314602657634e487b7160e01b5f525f60045260245ffd5b305f52607381538281f3fe730000000000000000000000000000000000000000301460806040525f80fdfea2646970667358221220ff45b8080809ba4f27f6c71aef9990d3a1a5e00d3f6f105aa6f8fe43fe039ef864736f6c63430008150033";
  readonly deployedBytecode: "0x730000000000000000000000000000000000000000301460806040525f80fdfea2646970667358221220ff45b8080809ba4f27f6c71aef9990d3a1a5e00d3f6f105aa6f8fe43fe039ef864736f6c63430008150033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/util/console.sol";
  readonly buildInfoId: "solc-0_8_21-01635e889ba6c40c9ebf98ff78fc54a4075ec8af";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["console"]: console$Type;
    ["contracts/util/console.sol:console"]: console$Type;
  }
}