// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface console$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "console";
  readonly sourceName: "contracts/util/console.sol";
  readonly abi: [];
  readonly bytecode: "0x60556032600b8282823980515f1a607314602657634e487b7160e01b5f525f60045260245ffd5b305f52607381538281f3fe730000000000000000000000000000000000000000301460806040525f80fdfea26469706673582212207073f75cb717417ee0d068bec56d395f1fc802576b10260fbd804ba186598c4a64736f6c63430008150033";
  readonly deployedBytecode: "0x730000000000000000000000000000000000000000301460806040525f80fdfea26469706673582212207073f75cb717417ee0d068bec56d395f1fc802576b10260fbd804ba186598c4a64736f6c63430008150033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/util/console.sol";
  readonly buildInfoId: "solc-0_8_21-c0965b163844844c2247be55fc35cf0807c72417";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["console"]: console$Type;
    ["contracts/util/console.sol:console"]: console$Type;
  }
}